name: dialogflow_flutter
description: Plugin for using DialogFLow in flutter applications
version: 1.0.0
homepage: https://github.com/GoyalSidhant/dialogflow_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  googleapis_auth: ^1.1.0
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter




  