name: dialogflow_flutter
description: Flutter plugn to use Dialogflow 
version: 0.0.2
homepage: https://github.com/GoyalSidhant/dialogflow_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

    
  
  http: ^0.13.3
  googleapis_auth: ^1.1.0
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  plugin:
    platforms:
      android:
        package: com.example.dialogflow_flutter
        pluginClass: DialogflowFlutterPlugin
      ios:
        pluginClass: DialogflowFlutterPlugin
      

  